# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import miller.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(default=miller.helpers.create_short_url, max_length=22, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('picture', models.URLField(blank=True, max_length=160, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(default=miller.helpers.create_short_url, max_length=22, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=140, unique=True)),
                ('abstract', models.CharField(blank=True, max_length=500, null=True)),
                ('contents', models.TextField(default=b'')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(b'draft', b'draft'), (b'shared', b'shared'), (b'public', b'public')], max_length=10)),
                ('authors', models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(related_name='watchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
