# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import miller.helpers
import miller.models.document
import simplemde.fields


class Migration(migrations.Migration):

    replaces = [(b'miller', '0001_initial'), (b'miller', '0002_auto_20160330_0938'), (b'miller', '0003_auto_20160330_1310'), (b'miller', '0004_auto_20160406_1229'), (b'miller', '0005_auto_20160407_1527'), (b'miller', '0006_auto_20160407_1534'), (b'miller', '0007_auto_20160407_1537'), (b'miller', '0008_auto_20160411_0817'), (b'miller', '0009_auto_20160411_1521'), (b'miller', '0010_auto_20160412_1037'), (b'miller', '0011_auto_20160418_1539'), (b'miller', '0012_auto_20160525_0805'), (b'miller', '0013_auto_20160525_0820'), (b'miller', '0014_auto_20160530_0630'), (b'miller', '0015_auto_20160531_0846'), (b'miller', '0016_auto_20160601_0630'), (b'miller', '0017_story_covers'), (b'miller', '0018_auto_20160902_0908'), (b'miller', '0019_tag_metadata')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(default=miller.helpers.create_short_url, max_length=22, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('picture', models.URLField(blank=True, max_length=160, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(default=miller.helpers.create_short_url, max_length=22, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=140, unique=True)),
                ('abstract', models.CharField(blank=True, max_length=500, null=True)),
                ('contents', models.TextField(default=b'')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(b'draft', b'draft'), (b'shared', b'shared'), (b'public', b'public')], max_length=10)),
                ('authors', models.ManyToManyField(blank=True, related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='watchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('category', models.CharField(choices=[(b'keyword', b'keyword'), (b'blog', b'blog'), (b'highlights', b'highlights'), (b'writing', b'writing')], default=b'keyword', max_length=32)),
                ('status', models.CharField(choices=[(b'hidden', b'keep this hidden'), (b'public', b'published tag')], default=b'public', max_length=10)),
                ('metadata', jsonfield.fields.JSONField(default=b'{"name": {"en_US": "", "fr_FR": ""}}')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, to=b'miller.Tag'),
        ),
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_copyright',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video', b'video'), (b'picture', b'picture'), (b'pdf', b'pdf')], max_length=24)),
                ('short_url', models.CharField(default=miller.helpers.create_short_url, max_length=22, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('contents', models.TextField()),
                ('copyrights', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('attachment', models.FileField(upload_to=miller.models.document.attachment_file_name)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='caption',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miller.Document'),
        ),
        migrations.AddField(
            model_name='caption',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miller.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='documents', through='miller.Caption', to=b'miller.Document'),
        ),
        migrations.AlterModelOptions(
            name='caption',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'captions'},
        ),
        migrations.AlterField(
            model_name='story',
            name='contents',
            field=simplemde.fields.SimpleMDEField(default=b'', verbose_name='mardown content'),
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=miller.models.document.attachment_file_name),
        ),
        migrations.AlterField(
            model_name='document',
            name='contents',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='copyrights',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'picture', b'picture'), (b'pdf', b'pdf')], max_length=24),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.CharField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'text', b'text'), (b'picture', b'picture'), (b'pdf', b'pdf'), (b'image', b'picture')], max_length=24),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-date_last_modified',), 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='caption',
            name='contents',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'text', b'text'), (b'picture', b'picture'), (b'pdf', b'pdf'), (b'image', b'picture'), (b'rich', b'rich')], max_length=24),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'text', b'text'), (b'picture', b'picture'), (b'pdf', b'pdf'), (b'image', b'picture'), (b'rich', b'rich'), (b'link', b'link')], max_length=24),
        ),
        migrations.AddField(
            model_name='story',
            name='covers',
            field=models.ManyToManyField(blank=True, related_name='covers', to=b'miller.Document'),
        ),
        migrations.AddField(
            model_name='story',
            name='metadata',
            field=jsonfield.fields.JSONField(default=b'{"abstract": {"fr": "", "en": ""}, "title": {"fr": "", "en": ""}}'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'text', b'text'), (b'picture', b'picture'), (b'pdf', b'pdf'), (b'image', b'picture'), (b'photo', b'picture'), (b'rich', b'rich'), (b'link', b'link'), (b'audiovisual', b'audiovisual')], max_length=24),
        ),
    ]
