# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 09:03
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0001_document_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
