# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0002_auto_20160330_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[(b'keyword', b'keyword'), (b'event', b'event')], default=b'keyword', max_length=32),
        ),
    ]
