# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0002_auto_20170614_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngrams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('segment', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(default=1)),
                ('documents', models.ManyToManyField(blank=True, to='miller.Document')),
            ],
        ),
    ]
