# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0003_auto_20160330_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover_copyright',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[(b'keyword', b'keyword'), (b'blog', b'blog'), (b'highlights', b'highlights'), (b'writing', b'writing')], default=b'keyword', max_length=32),
        ),
    ]
