# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import miller.helpers
import miller.models.document


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miller', '0004_auto_20160406_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video', b'video')], max_length=24)),
                ('short_url', models.CharField(default=miller.helpers.create_short_url, max_length=22, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('copyrights', models.TextField()),
                ('url', models.URLField(max_length=500, unique=True)),
                ('attachment', models.FileField(upload_to=miller.models.document.attachment_file_name)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='caption',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miller.Document'),
        ),
        migrations.AddField(
            model_name='caption',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miller.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='documents',
            field=models.ManyToManyField(blank=True, through='miller.Caption', to='miller.Document'),
        ),
    ]
