# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 07:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0004_auto_20170619_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='metadata contents'),
        ),
    ]
