# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 08:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0005_story_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text=b'JSON format', verbose_name='metadata contents'),
        ),
    ]
