# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 15:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0006_auto_20170703_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='orcid',
            field=models.CharField(blank=True, max_length=24, validators=[django.core.validators.RegexValidator(message=b"ORCID should contain only numbers and '-' sign", regex=b'^[\\d\\-]+$')]),
        ),
    ]
