# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0006_auto_20160407_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video', b'video'), (b'picture', b'picture')], max_length=24),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
