# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0007_author_orcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'crossref', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'text', b'text'), (b'picture', b'picture'), (b'pdf', b'pdf'), (b'image', b'image'), (b'photo', b'photo'), (b'rich', b'rich'), (b'link', b'link'), (b'audiovisual', b'audiovisual'), (b'entity', b'entity: see data type property'), (b'timeline', b'timeline')], max_length=24),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[(b'keyword', b'keyword'), (b'blog', b'blog'), (b'highlights', b'highlights'), (b'writing', b'writing'), (b'collection', b'collection'), (b'publishing', b'publishing'), (b'SDG', b'SDG indicator')], default=b'keyword', max_length=32),
        ),
    ]
