# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0007_auto_20160407_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[(b'hidden', b'keep this hidden'), (b'public', b'published tag')], default=b'public', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
