# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 15:21
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0008_auto_20160411_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='contents',
            field=simplemde.fields.SimpleMDEField(default=b'', verbose_name='mardown content'),
        ),
    ]
