# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 09:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import miller.models.author


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0008_auto_20170822_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=miller.models.author.initial_data),
        ),
    ]
