# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-04 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0009_auto_20170904_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[(b'keyword', b'keyword'), (b'blog', b'blog'), (b'highlights', b'highlights'), (b'writing', b'writing'), (b'collection', b'collection'), (b'publishing', b'publishing'), (b'static', b'static page')], default=b'keyword', max_length=32),
        ),
    ]
