# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0010_auto_20210916_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='usage_statistics',
            field=models.IntegerField(default=0),
        ),
    ]
