# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0011_auto_20210607_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
