# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-27 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0011_tag_usage_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[(b'viewed', b'viewed'), (b'downloaded', b'downloaded')], max_length=24)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miller.Story')),
            ],
        ),
        migrations.AddField(
            model_name='hitcount',
            name='story_hit',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='miller.StoryHit'),
        ),
    ]
