# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0012_auto_20160525_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
