# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0012_auto_20211027_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='euro_usage_statistics',
            field=models.IntegerField(default=0),
        ),
    ]
