# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0013_auto_20160525_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-date_last_modified',), 'verbose_name_plural': 'stories'},
        ),
    ]
