# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0014_auto_20160530_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='contents',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'text', b'text'), (b'picture', b'picture'), (b'pdf', b'pdf'), (b'image', b'picture'), (b'rich', b'rich')], max_length=24),
        ),
    ]
