# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0015_auto_20160531_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'text', b'text'), (b'picture', b'picture'), (b'pdf', b'pdf'), (b'image', b'picture'), (b'rich', b'rich'), (b'link', b'link')], max_length=24),
        ),
    ]
