# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0016_auto_20160601_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='covers',
            field=models.ManyToManyField(blank=True, related_name='covers', to='miller.Document'),
        ),
    ]
