# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import miller.models.story


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0023_auto_20160912_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to=miller.models.story.user_path),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[(b'draft', b'draft'), (b'shared', b'shared'), (b'public', b'public'), (b'editing', b'editing'), (b'review', b'review')], max_length=10),
        ),
    ]
