# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import miller.models.story
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0024_auto_20160916_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='bibliography',
            field=models.FileField(blank=True, null=True, upload_to=miller.models.story.user_path),
        ),
        migrations.AlterField(
            model_name='story',
            name='contents',
            field=simplemde.fields.SimpleMDEField(blank=True, default=b'', verbose_name='mardown content'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[(b'draft', b'draft'), (b'shared', b'shared'), (b'public', b'public'), (b'editing', b'editing'), (b'review', b'review')], default=b'draft', max_length=10),
        ),
    ]
