# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0025_auto_20160921_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contents',
            field=models.TextField(blank=True, default=b'{"provider_url": "", "description": "", "title": "", "html": "", "details": {}, "provider_name": "", "type": "rich"}', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'text', b'text'), (b'picture', b'picture'), (b'pdf', b'pdf'), (b'image', b'image'), (b'photo', b'photo'), (b'rich', b'rich'), (b'link', b'link'), (b'audiovisual', b'audiovisual')], max_length=24),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[(b'keyword', b'keyword'), (b'blog', b'blog'), (b'highlights', b'highlights'), (b'writing', b'writing'), (b'collection', b'collection')], default=b'keyword', max_length=32),
        ),
    ]
