# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-05 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0026_auto_20160929_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='collection', to='miller.Story'),
        ),
    ]
