# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0026_auto_20160929_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name_plural': 'mentions',
            },
        ),
        migrations.AlterField(
            model_name='story',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, default=b'{"abstract": {"fr": "", "en": ""}, "title": {"fr": "", "en": ""}}'),
        ),
        migrations.AddField(
            model_name='mention',
            name='from_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_mentions', to='miller.Story'),
        ),
        migrations.AddField(
            model_name='mention',
            name='to_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_mentions', to='miller.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='mentions',
            field=models.ManyToManyField(related_name='mentioned_to', through='miller.Mention', to='miller.Story'),
        ),
    ]
