# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-12 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0027_auto_20161012_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='mentions',
            new_name='stories',
        ),
    ]
