# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-14 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0028_auto_20161012_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='abstract',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
