# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import miller.models.document


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0029_auto_20161014_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='snapshot',
            field=models.FileField(blank=True, null=True, upload_to=miller.models.document.snapshot_attachment_file_name),
        ),
    ]
