# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0030_auto_20161020_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[(b'draft', b'draft'), (b'shared', b'shared'), (b'public', b'public'), (b'editing', b'editing'), (b'review', b'review'), (b'deleted', b'deleted')], default=b'draft', max_length=10),
        ),
    ]
