# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0031_auto_20161021_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mimetype',
            field=models.CharField(default=b'', max_length=127),
        ),
    ]
