# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0033_auto_20161025_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
