# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-08 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0034_document_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='contents',
            field=models.TextField(blank=True, default=b'', verbose_name='mardown content'),
        ),
        migrations.AlterField(
            model_name='story',
            name='metadata',
            field=models.TextField(blank=True, default=b'{"abstract": {"fr": "", "en": ""}, "title": {"fr": "", "en": ""}}'),
        ),
    ]
