# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0035_auto_20161108_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='metadata',
            field=models.TextField(blank=True, default=b'{"name": {}}', null=True),
        ),
    ]
