# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0036_auto_20161109_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='metadata',
            field=models.TextField(blank=True, default=b'{\n "name": {\n  "de_DE": "", \n  "en_US": "", \n  "fr_FR": ""\n }\n}', null=True),
        ),
    ]
