# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-09 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0037_auto_20161109_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contents',
            field=models.TextField(blank=True, default=b'{\n "provider_url": "", \n "description": "", \n "title": "", \n "html": "", \n "details": {}, \n "provider_name": "", \n "type": "rich"\n}', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='metadata',
            field=models.TextField(blank=True, default=b'{\n "abstract": {\n  "de_DE": "", \n  "en_US": "", \n  "fr_FR": ""\n }, \n "title": {\n  "de_DE": "", \n  "en_US": "", \n  "fr_FR": ""\n }\n}'),
        ),
    ]
