# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miller', '0038_auto_20161109_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('affiliation', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, default=b'{\n "lastname": "", \n "firstname": ""\n}', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorship', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
