# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0039_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, max_length=140, unique=True),
        ),
    ]
