# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0040_auto_20161114_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=150, unique=True),
        ),
    ]
