# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0041_auto_20161122_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=140, unique=True),
        ),
    ]
