# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miller', '0042_auto_20161122_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'pending', b'pending acceptation'), (b'private', b'accepted, privately visible'), (b'public', b'accepted, publicly visible'), (b'deleted', b'deleted')], db_index=True, default=b'pending', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('contents', models.TextField(blank=True, default=b'{\n "content": "", \n "annotation": {}, \n "title": ""\n}')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[(b'draft', b'draft'), (b'shared', b'shared'), (b'public', b'public'), (b'editing', b'editing'), (b'review', b'review'), (b'deleted', b'deleted')], db_index=True, default=b'draft', max_length=10),
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='miller.Story'),
        ),
    ]
