# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0042_auto_20161110_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to='miller.Author'),
        ),
    ]
