# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0043_auto_20161128_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.CharField(choices=[(b'W', b'weekly'), (b'M', b'monthly'), (b'0', b'never')], db_index=True, default=b'W', max_length=1),
        ),
    ]
