# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0044_profile_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_last_notified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
