# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 09:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0050_auto_20161213_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='pertincence',
            new_name='pertinence',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pertincence_score',
        ),
        migrations.AddField(
            model_name='review',
            name='pertinence_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='argumentation_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='clarity_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='innovation_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='interdiciplinarity_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='interest_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='methodology_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='originality_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='references_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[(b'initial', b'initial'), (b'draft', b'draft'), (b'private', b'private'), (b'public', b'public')], default=b'initial', max_length=8),
        ),
        migrations.AlterField(
            model_name='review',
            name='structure_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='thematic_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='story',
            name='metadata',
            field=models.TextField(blank=True, default=b'{\n "abstract": {\n  "de_DE": "", \n  "en_GB": "", \n  "en_US": "", \n  "fr_FR": ""\n }, \n "title": {\n  "de_DE": "", \n  "en_GB": "", \n  "en_US": "", \n  "fr_FR": ""\n }\n}'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='metadata',
            field=models.TextField(blank=True, default='{\n "name": {\n  "de_DE": "", \n  "en_GB": "", \n  "en_US": "", \n  "fr_FR": ""\n }\n}', null=True),
        ),
    ]
