# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0052_auto_20161214_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
