# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0053_auto_20161214_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text=b'This has been automatically assigned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='assignee',
            field=models.ForeignKey(help_text=b"To include users in this list, add them to the groups 'editors' or 'reviewers'", on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='story',
            field=models.ForeignKey(help_text=b"This shows only stories having status 'review' or 'editing'", on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='miller.Story'),
        ),
    ]
