# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0057_auto_20161216_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
