# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0058_story_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('contents', models.TextField(blank=True, default=b'', verbose_name='mardown content')),
            ],
        ),
    ]
