# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0059_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='stories', to='miller.Author'),
        ),
    ]
