# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import miller.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0062_auto_20170221_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='short_url',
            field=models.CharField(db_index=True, default=miller.helpers.create_short_url, max_length=22, unique=True),
        ),
    ]
