# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0064_auto_20170303_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[(b'draft', b'draft'), (b'shared', b'shared'), (b'public', b'public'), (b'editing', b'editing'), (b'review', b'review'), (b'deleted', b'deleted'), (b'pending', b'pending')], db_index=True, default=b'draft', max_length=10),
        ),
    ]
