# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import miller.models.review


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0065_auto_20170310_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='acceptance',
            field=models.CharField(choices=[(b'initial', b'initial'), (b'accepted', b'accepted'), (b'conflict', b'conflict of interest'), (b'busy', b'refused - other reason')], default=b'initial', max_length=8),
        ),
        migrations.AlterField(
            model_name='review',
            name='due_date',
            field=models.DateTimeField(blank=True, default=miller.models.review.assign_due_date, null=True),
        ),
    ]
