# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import miller.models.review


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0066_auto_20170407_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='due_date',
            field=models.DateTimeField(blank=True, default=miller.models.review.assign_due_date),
        ),
    ]
