# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0067_auto_20170407_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='assigned_by',
            field=models.ForeignKey(default=1, help_text=b'This has been automatically assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
