# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 11:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0069_auto_20170411_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
