# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0070_document_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='stories', through='miller.Caption', to='miller.Document'),
        ),
    ]
