# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0071_auto_20170421_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='contents',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[(b'initial', b'initial'), (b'draft', b'draft'), (b'private', b'private'), (b'public', b'public'), (b'refusal', b'refusal'), (b'bounce', b'bounce'), (b'complete', b'complete'), (b'approved', b'approved')], default=b'initial', max_length=8),
        ),
    ]
