# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0073_auto_20170428_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documents',
            field=models.ManyToManyField(related_name='_document_documents_+', to='miller.Document'),
        ),
    ]
