# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0074_document_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[(b'bibtex', b'bibtex'), (b'crossref', b'bibtex'), (b'video-cover', b'video interview'), (b'video', b'video'), (b'text', b'text'), (b'picture', b'picture'), (b'pdf', b'pdf'), (b'image', b'image'), (b'photo', b'photo'), (b'rich', b'rich'), (b'link', b'link'), (b'audiovisual', b'audiovisual'), (b'entity', b'entity: see data type property')], max_length=24),
        ),
    ]
