# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0075_auto_20170502_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='_document_documents_+', to='miller.Document'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[(b'draft', b'draft'), (b'shared', b'shared'), (b'public', b'public'), (b'deleted', b'deleted'), (b'pending', b'pending review'), (b'editing', b'editing'), (b'review', b'review'), (b'reviewdone', b'review done'), (b'preprint', b'pre print')], db_index=True, default=b'draft', max_length=10),
        ),
    ]
