# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0076_auto_20170504_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
