# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import miller.models.document


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0077_auto_20170505_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=miller.models.document.attachment_file_name),
        ),
        migrations.AlterField(
            model_name='document',
            name='snapshot',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=miller.models.document.snapshot_attachment_file_name),
        ),
    ]
