# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0078_auto_20170511_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
