# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 16:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0079_author_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
