# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0080_tag_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='metadata',
        ),
    ]
